# Generated by Django 3.2.5 on 2022-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadda_app', '0003_songinfo_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='song_lyrics',
            field=models.TextField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='song_title',
            field=models.CharField(max_length=222, unique=True),
        ),
    ]
