# Generated by Django 3.2.5 on 2022-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadda_app', '0005_auto_20220713_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
