# Generated by Django 3.2.5 on 2022-07-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadda_app', '0006_stories_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
